### ISSUE TITLE
No completion for arrays in Qute templates

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/quarkus-ls#517] opened 2022-01-06 14:18 UTC
Given 
```java
package org.acme;
public class Stuff  {
    public String[] labels;
}
``` 
in the following template, no completion is proposed for the `labels` properties:

```
{@org.acme.Stuff stuff}
{stuff.labels.|}
```

(initially mentioned as Problem 10 in https://github.com/redhat-developer/quarkus-ls/issues/432#issue-1061460395)

**Comment by angelozerr** [comment] 2022-01-06 14:22
I think you want to have just `length `as property, is that?

**Comment by angelozerr** [comment] 2022-01-12 13:51
Duplicate of https://github.com/redhat-developer/quarkus-ls/issues/525

**Closed by angelozerr** 2022-01-12 13:51 UTC
Labels: bug, completion, qute, template-file
